[package]
name = "vent-assets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vent-sdk = { path = "../vent-sdk" }
vent-rendering = { path = "../vent-rendering"}

image = "0.24.7"

bytemuck = { version = "1.14.0" }
log = "0.4"
cfg-if = "1"

ash = { version= "0.37.3", default-features = false, features = ["linked"] }

# model
tobj = { version = "4.0.0", features = ["async"] }
gltf = "1.3.0"

