name: Pull Reqeust

on:
  pull_request:
    branches: [ "master" ]
    types:
      - labeled

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: ${{ github.event.label.name == 'rust' }}
    name: Rust
    uses: ./.github/workflows/rust.yml
