name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    name: Test `cargo check/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Vulkan
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.268.0
          vulkan-components: SPIRV-Tools, Glslang
          vulkan-use-cache: true
      
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
      - name: Run test
        run: cargo test --verbose