name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Vulkan SDK and libxcb
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt-get update
          sudo apt-get install -y vulkan-sdk libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      - name: Run test
        run: cargo test --verbose
  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Vulkan SDK
        run: choco install -y --no-progress vulkan-sdk
      - name: Find and add the SDK to Path
        run: |
          $path = (Get-ChildItem -Path C:/VulkanSDK -Directory | select FullName -first 1).FullName
          echo "${path}\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      - name: Run test
        run: cargo test --verbose
